'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>s?new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'';
const safe=s=>{try{return new URL(s).protocol==='https:';}catch{return false;}};
function link(url,title,cls=''){return safe(url)?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`:`<span class="unavailable">${esc(title)} · available when your teacher releases it</span>`;}
const storageKey='north-star-summit-2026-27-work', progressKey='north-star-summit-2026-27-checkmarks';
let personal={sheet:'',notebook:''},done={};
function validPersonal(kind,url){if(!url)return true;try{const u=new URL(url),template=kind==='sheet'?COURSE.links.sheetTemplate:COURSE.links.notebookTemplate,tid=template?.match(/\/(?:d|drive)\/([\w-]+)/)?.[1],match=kind==='sheet'?u.pathname.match(/^\/spreadsheets\/d\/([\w-]+)(?:\/(?:edit|view))?\/?$/):u.pathname.match(/^\/drive\/([\w-]+)\/?$/);return u.protocol==='https:'&&u.hostname===(kind==='sheet'?'docs.google.com':'colab.research.google.com')&&!!match&&match[1]!==tid;}catch{return false;}}
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');for(const k of ['sheet','notebook'])if(typeof saved[k]==='string'&&validPersonal(k,saved[k]))personal[k]=saved[k];const checks=JSON.parse(localStorage.getItem(progressKey)||'{}');for(const m of COURSE.modules)done[m.id]=checks[m.id]===true;}catch{}
function renderPersonal(){document.getElementById('personal-actions').innerHTML=['sheet','notebook'].map(k=>personal[k]?link(personal[k],k==='sheet'?'Open my Sheet':'Open my Colab notebook','button'): `<a href="#work-setup" class="button secondary" data-setup>${k==='sheet'?'Add my Sheet link':'Add my notebook link'}</a>`).join('');document.querySelectorAll('[data-setup]').forEach(a=>a.addEventListener('click',()=>{document.getElementById('work-setup').open=true;}));for(const k of ['sheet','notebook'])document.getElementById(k+'-url').value=personal[k];}
function savePersonal(next){personal=next;let persisted=true;try{localStorage.setItem(storageKey,JSON.stringify(personal));}catch{persisted=false;}renderPersonal();document.getElementById('links-message').textContent=persisted?'Your shortcuts are saved on this browser.':'Your shortcuts work for this visit; this browser could not save them.';}
document.getElementById('personal-links').addEventListener('submit',e=>{e.preventDefault();const next={sheet:document.getElementById('sheet-url').value.trim(),notebook:document.getElementById('notebook-url').value.trim()};if(!validPersonal('sheet',next.sheet)||!validPersonal('notebook',next.notebook)){document.getElementById('links-message').textContent='Use links to your personal Google Sheet and Colab notebook, not the class templates or copy links.';return;}savePersonal(next);});
document.getElementById('clear-links').addEventListener('click',()=>{personal={sheet:'',notebook:''};done={};try{localStorage.removeItem(storageKey);localStorage.removeItem(progressKey);}catch{}renderPersonal();renderLessons();document.getElementById('links-message').textContent='Shortcuts and checkmarks cleared. Your Google files and submitted Forms have not changed.';});
// Personal file links are saved only in this browser, never in the public course data.
function renderLessons(){let index=0;document.getElementById('lesson-list').innerHTML=COURSE.phases.map(p=>`<h3 class="phase-label">Phase ${p.id}: ${esc(p.title)}</h3>`+COURSE.modules.filter(m=>m.phase===p.id).map(m=>{index++;const resources=m.resources.map(id=>COURSE.resources.find(r=>r.id===id)).filter(Boolean);const primary=resources.map(r=>link(r.url,r.title,'button secondary')).join('');const work=m.workKind?`<a href="#my-work" class="button">Open my ${m.workKind==='sheet'?'Sheet':'Colab notebook'}</a>`:'';return `<details class="lesson" id="lesson-${esc(m.id)}" ${m.id==='welcome'?'open':''}><summary><span class="number">${index}</span><span class="lesson-title">${esc(m.title)}<span class="lesson-meta">${esc(m.month)} · ${m.id==='welcome'?'Get to know each other':m.id==='AI'?'AI and your judgment':m.id==='A06'?'Final presentation':m.workKind==='sheet'?'Google Sheets':'Google Colab'} · Due ${fmt(m.due)} <span class="marked" data-mark="${esc(m.id)}">${done[m.id]?'✓ You marked this submitted':''}</span></span></span></summary><div class="lesson-body"><p class="focus">${esc(m.focus)}</p><div class="action-row">${primary}${work}</div><h3>Try this</h3><p>${esc(m.practice)}</p><h3>${m.id==='welcome'?'Tell us about yourself':'Questions to answer'}</h3><ol class="questions">${m.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol>${(m.bonuses||[]).map(b=>`<details class="bonus"><summary>${esc(b.title)}</summary><p>${esc(b.text)}</p></details>`).join('')}<p class="small"><b>Before you submit:</b> ${esc(m.check)}</p><div class="submit-block"><h3>${m.id==='welcome'?'Send us your goals':'Turn in this assignment'}</h3><p>${esc(m.deliverable)}</p>${link(m.submissionUrl,m.id==='welcome'?'Open the goals Form':`Open the ${m.id} answer Form`,'button')}<label class="completion"><input type="checkbox" data-complete="${esc(m.id)}" ${done[m.id]?'checked':''}>I submitted this Google Form.</label><p class="small">This checkmark is a reminder on this browser. Your teachers receive the answers only when you press Submit in the Google Form.</p><p class="small" data-progress-status="${esc(m.id)}" role="status"></p></div></div></details>`;}).join('')).join('');}
document.getElementById('lesson-list').addEventListener('change',e=>{const id=e.target.dataset.complete;if(!id)return;done[id]=e.target.checked;let saved=true;try{localStorage.setItem(progressKey,JSON.stringify(done));}catch{saved=false;}document.querySelector(`[data-mark="${id}"]`).textContent=done[id]?'✓ You marked this submitted':'';document.querySelector(`[data-progress-status="${id}"]`).textContent=saved?'Reminder saved on this browser.':'Reminder changed for this visit; this browser could not save it.';});
renderPersonal();renderLessons();
document.getElementById('phase-syllabus').innerHTML=COURSE.phases.map(p=>`<div class="phase-description"><h3>Phase ${p.id}: ${esc(p.title)}</h3><p>${esc(p.description)}</p></div>`).join('');
document.getElementById('schedule-rows').innerHTML=COURSE.workshops.map(w=>`<tr><td>${fmt(w.date)}, ${w.date.slice(0,4)}</td><td>${esc(w.title)} <span class="small">(${w.minutes} min)</span></td></tr>`).join('');
document.getElementById('resource-list').innerHTML=COURSE.resources.map(r=>`<div class="resource">${link(r.url,r.title)}<p>${esc(r.note)}</p></div>`).join('');
document.getElementById('data-table').innerHTML=`<thead><tr>${DATA.columns.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${DATA.preview.map(r=>`<tr>${DATA.columns.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody>`;
// Keep section navigation inside the Apps Script iframe rather than navigating its parent.
document.addEventListener('click',event=>{const a=event.target.closest('a[href^="#"]');if(!a)return;const target=document.getElementById(a.getAttribute('href').slice(1));if(!target)return;event.preventDefault();if(target.tagName==='DETAILS')target.open=true;target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});
