'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>s?new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'';
const safe=s=>{try{return new URL(s).protocol==='https:';}catch{return false;}};
function link(url,title,cls=''){return safe(url)?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`:`<span class="unavailable">${esc(title)} · available when your teacher releases it</span>`;}
// Gemini: once links.controlsCsv is set, Mr. Hayward's course-controls Sheet decides whether the starter prompt appears; until then links.geminiPrompt is shown.
function geminiBlock(){return `<div class="gemini" id="gemini"><h3>Working with Gemini</h3><ol class="steps"><li><b>Open Gemini with your school Google account.</b> ${link(COURSE.links.gemini,'Open Gemini','button secondary')}<br><span class="small">If Gemini says it is not available for your account, tell your teacher. They will give you a sample Gemini response to check instead.</span></li><li><b>Copy the starter prompt.</b> The button copies the prompt and all 2,001 rows of data together.<div id="gemini-prompt" class="gemini-prompt"></div></li><li><b>Paste it into Gemini and send.</b> Gemini should report 2,001 rows, five columns, and dates from 2017-10-10 to 2024-09-29. If it reports fewer rows, ${link(COURSE.links.dataCsv,'download the data file')}, click <b>+</b> in Gemini, attach it, and ask again.</li><li><b>Ask Gemini to redo</b> one spreadsheet question and one Python or chart task. Then check two of its numbers yourself.</li></ol><p class="small">In Colab you can also use the Gemini button beside your notebook. It can see the data your notebook already loaded.</p></div>`;}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
async function loadGemini(){const box=document.getElementById('gemini-prompt');if(!box)return;const waiting='<p class="small">Mr. Hayward will release the starter prompt when we begin this lesson.</p>';try{let text=(COURSE.links.geminiPrompt||'').trim();if(safe(COURSE.links.controlsCsv)){const r=await fetch(COURSE.links.controlsCsv,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const row=parseCsv(await r.text()).find(x=>x[0]==='gemini_prompt');text=(row?.[1]||'').trim();}if(!text){box.innerHTML=waiting;return;}box.innerHTML=`<textarea id="gemini-text" readonly rows="7" aria-label="Starter Gemini prompt">${esc(text)}</textarea><div class="action-row"><button type="button" class="button secondary" id="copy-prompt">Copy the prompt and data</button><span class="small" id="copy-status" role="status"></span></div>`;document.getElementById('copy-prompt').addEventListener('click',async()=>{const area=document.getElementById('gemini-text'),status=document.getElementById('copy-status');status.textContent='Copying…';try{const data=await (await fetch(COURSE.links.dataCsv)).text();await navigator.clipboard.writeText(area.value+'\n\n'+data.trim());status.textContent='Copied the prompt and all the data. Paste it into Gemini.';}catch{area.select();status.textContent='Copy did not work here. Copy the prompt with Ctrl+C (or Cmd+C), then attach the data file in Gemini.';}});}catch{box.innerHTML='<p class="small">The starter prompt did not load. Refresh the page, or ask your teacher for it.</p>';}}

const storageKey='north-star-summit-2026-27-work';
let personal={sheet:'',notebook:''};
function validPersonal(kind,url){if(!url)return true;try{const u=new URL(url),template=kind==='sheet'?COURSE.links.sheetTemplate:COURSE.links.notebookTemplate,tid=template?.match(/\/(?:d|drive)\/([\w-]+)/)?.[1],match=kind==='sheet'?u.pathname.match(/^\/spreadsheets\/d\/([\w-]+)(?:\/(?:edit|view))?\/?$/):u.pathname.match(/^\/drive\/([\w-]+)\/?$/);return u.protocol==='https:'&&u.hostname===(kind==='sheet'?'docs.google.com':'colab.research.google.com')&&!!match&&match[1]!==tid;}catch{return false;}}
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');for(const k of ['sheet','notebook'])if(typeof saved[k]==='string'&&validPersonal(k,saved[k]))personal[k]=saved[k];}catch{}
function renderPersonal(){document.getElementById('personal-actions').innerHTML=['sheet','notebook'].map(k=>personal[k]?link(personal[k],k==='sheet'?'Open my Sheet':'Open my Colab notebook','button'): `<a href="#work-setup" class="button secondary" data-setup>${k==='sheet'?'Add my Sheet link':'Add my notebook link'}</a>`).join('');document.querySelectorAll('[data-setup]').forEach(a=>a.addEventListener('click',()=>{document.getElementById('work-setup').open=true;}));for(const k of ['sheet','notebook'])document.getElementById(k+'-url').value=personal[k];}
function savePersonal(next){personal=next;let persisted=true;try{localStorage.setItem(storageKey,JSON.stringify(personal));}catch{persisted=false;}renderPersonal();document.getElementById('links-message').textContent=persisted?'Your shortcuts are saved on this browser.':'Your shortcuts work for this visit; this browser could not save them.';}
document.getElementById('personal-links').addEventListener('submit',e=>{e.preventDefault();const next={sheet:document.getElementById('sheet-url').value.trim(),notebook:document.getElementById('notebook-url').value.trim()};if(!validPersonal('sheet',next.sheet)||!validPersonal('notebook',next.notebook)){document.getElementById('links-message').textContent='Use links to your personal Google Sheet and Colab notebook, not the class templates or copy links.';return;}savePersonal(next);});
document.getElementById('clear-links').addEventListener('click',()=>{personal={sheet:'',notebook:''};try{localStorage.removeItem(storageKey);localStorage.removeItem('north-star-summit-2026-27-checkmarks');}catch{}renderPersonal();renderLessons();document.getElementById('links-message').textContent='Saved shortcuts cleared. Your Google files and submitted Forms have not changed.';});
// Personal file links are saved only in this browser, never in the public course data.
function renderLessons(){let index=0;document.getElementById('lesson-list').innerHTML=COURSE.phases.map(p=>`<h3 class="phase-label">Phase ${p.id}: ${esc(p.title)}</h3>`+COURSE.modules.filter(m=>m.phase===p.id).map(m=>{index++;const resources=m.resources.map(id=>COURSE.resources.find(r=>r.id===id)).filter(Boolean);const primary=resources.map(r=>link(r.url,r.title,'button secondary')).join('');const work=m.workKind?`<a href="#my-work" class="button">Open my ${m.workKind==='sheet'?'Sheet':'Colab notebook'}</a>`:'';return `<details class="lesson" id="lesson-${esc(m.id)}" ${m.id==='welcome'?'open':''}><summary><span class="number">${index}</span><span class="lesson-title">${esc(m.title)}<span class="lesson-meta">${esc(m.month)} · ${m.id==='welcome'?'Get to know each other':m.id==='AI'?'AI and your judgment':m.id==='A06'?'Final presentation':m.workKind==='sheet'?'Google Sheets':'Google Colab'} · Due ${fmt(m.due)}</span></span></summary><div class="lesson-body"><p class="focus">${esc(m.focus)}</p><div class="action-row">${primary}${work}</div><h3>Dates for this assignment</h3><p class="small">Questions by ${fmt(m.questionsDue)} · Submit by ${fmt(m.due)} · Feedback by ${fmt(m.feedbackDue)}. All dates tentative.</p>${m.checkpoints?`<ul class="small">${m.checkpoints.map(x=>`<li>${fmt(x.date)}: ${esc(x.label)}</li>`).join('')}</ul>`:''}<h3>Try this</h3><p>${esc(m.practice)}</p><h3>${m.id==='welcome'?'Tell us about yourself':'Questions to answer'}</h3><ol class="questions">${m.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol>${(m.bonuses||[]).map(b=>`<details class="bonus"><summary>${esc(b.title)}</summary><p>${esc(b.text)}</p></details>`).join('')}${m.id==='AI'?geminiBlock():''}<p class="small"><b>Before you submit:</b> ${esc(m.check)}</p><div class="submit-block"><h3>${m.id==='welcome'?'Send us your goals':'Turn in this assignment'}</h3><p>${esc(m.deliverable)}</p>${link(m.submissionUrl,m.id==='welcome'?'Open the goals Form':`Open the ${m.id} answer Form`,'button')}<p class="small">Submit inside Google Forms. Its confirmation page is your receipt. This website does not track your identity or submission status.</p></div></div></details>`;}).join('')).join('');loadGemini();}
renderPersonal();renderLessons();
document.getElementById('phase-syllabus').innerHTML=COURSE.phases.map(p=>`<div class="phase-description"><h3>Phase ${p.id}: ${esc(p.title)}</h3><p>${esc(p.description)}</p></div>`).join('');
document.getElementById('schedule-rows').innerHTML=COURSE.workshops.map(w=>`<tr><td>${fmt(w.date)}, ${w.date.slice(0,4)}</td><td>${esc(w.title)} <span class="small">(${w.minutes} min)</span></td></tr>`).join('');
document.getElementById('resource-list').innerHTML=COURSE.resources.map(r=>`<div class="resource">${link(r.url,r.title)}<p>${esc(r.note)}</p></div>`).join('');
document.getElementById('data-table').innerHTML=`<thead><tr>${DATA.columns.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${DATA.preview.map(r=>`<tr>${DATA.columns.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody>`;
// Keep section navigation inside the Apps Script iframe rather than navigating its parent.
document.addEventListener('click',event=>{const a=event.target.closest('a[href^="#"]');if(!a)return;const target=document.getElementById(a.getAttribute('href').slice(1));if(!target)return;event.preventDefault();if(target.tagName==='DETAILS')target.open=true;target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});

document.getElementById('syllabus-files').innerHTML=link(COURSE.links.syllabusDoc,'Open the editable Google syllabus','button secondary')+link(COURSE.links.syllabusPdf,'View the syllabus PDF','button secondary');
document.getElementById('questions-form').innerHTML=link(COURSE.links.questionsForm,'Ask a question or check in','button secondary');
